### ISSUE TITLE
Performance for games

### ISSUE THREAD

**Issue by sabotage3d** [InteractiveComputerGraphics/PositionBasedDynamics#29]
Hi,
I build the library and the demos and everything works fine. I am trying to evaluate if the library would be fast enough for in-game use. I am mostly intersted in the tetra based solids. I tried all the demos but the most interesting was the SceneLoaderDemo with the DeformableSolidCollisionScene. At the moment it seems that the tetra armadillo is solving quite slow in both FEM and Volume constraints modes. Is there anything that could be optimized for realtime applications? Currently the armadillo has only around 4k tetras compared to tests from Carbon Tetrahedron library where they can achieve sims with 24Hz with 300,000 tets.

**Comment by janbender** [comment]
Did you measure the time using our library? Just watching the demo is not a good comparison since our visualization is rather slow but not the simulation. You can find some results in our paper "Position-Based Simulation of Continuous Materials".

For a good comparison with the Carbon library it would be good to know which method they use for simulation and how accurate their solver is. If you reduce the number of iterations and make some simplifications I am sure that our library will get significantly faster.

**Comment by sabotage3d** [comment]
I haven't actually measure it properly. But if I set the solid method to none the display updates fast enough where changing between FEM and volume constraints is really slow something like 10-20 seconds per frame on a 24 core machine. If I reduce the time-step to something like 1/24.0 the simulation becomes unstable. I also noticed the solids don't have self-collisions. Is there a CCD algorithm for self-collisions in the library? I am not sure what their method is exactly but it is looks like volume constraints or just a mass spring system. They use the tetras to preserve the volume and use cloth like solve for the outer surface of the mesh. I also tried the tetras in Bullet Physics and for a single core and self-collisions they are significantly faster than the PositionBasedDynamics approach on multiple cores. What approach would you recommend for proper benchmarking?

**Comment by janbender** [comment]
Did you measure the time using our library? Just watching the demo is 
not a good comparison since our visualization is rather slow but not the 
simulation. You can find some results in our paper "Position-Based 
Simulation of Continuous Materials".

For a good comparison with the Carbon library it would be good to know 
which method they use for simulation and how accurate their solver is. 
If you reduce the number of iterations and make some simplifications I 
am sure that our library will get significantly faster.

**Comment by janbender** [comment]
If you need 10-20 seconds per frame, then something went definitely wrong. Did you build the Release version? Is parallelization activated?

**Comment by sabotage3d** [comment]
Yeah I build in Release with OpenMP support and I can see that all the threads are being used. Maybe I need to change the precision? I am on a Linux machine with 16 cores/ 32 threads.

**Comment by janbender** [comment]
In the current version I added a time measurement. Maybe you can try to measure some timings and tell me how much time a demo requires.
