### ISSUE TITLE
Using floats instead of doubles.

### ISSUE THREAD

**Issue by mkanakis** [InteractiveComputerGraphics/PositionBasedDynamics#35]
Happy new year,

If I comment the following line:

`define USE_DOUBLE`

in Common.h 

Proceeds into else condition:
`#else
typedef float Real;
#define REAL_MAX FLT_MAX
#define REAL_MIN FLT_MIN
#endif`

This is supposed to exist for working with floats. But Simulation does not build. 
It throws : `Error	C2338	YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY`

in Matrix.h 

Is this a known issue? Any workarounds?

P.S. For anyone visualizing with OpenGL, according to this [question](http://gamedev.stackexchange.com/questions/135152/opengl-application-not-working-on-amd/135253#135253) I asked and the answer following, try avoiding double precision numbers which PositionBasedDynamics uses by default.

**Comment by louen** [comment]
Hi @mkanakis . It seems it's still Christmas after all, because I just fixed your problem :stuck_out_tongue: 

I use the PBD library with floats too, and I had to fix a few things in the code for it to work.

I submitted a patch a few days ago, you can check it out as pull request #34.
If you're interested just grab the version from my fork. I hope the maintainers of this library will integrate it soon to their version.

Cheers,

**Comment by mkanakis** [comment]
Wow, Christmas present indeed!

I will check it out and I will tell you if any issues occur. 

Also, did you move over to floats for the same reason I am trying to?

Thanks.

**Comment by louen** [comment]
> Also, did you move over to floats for the same reason I am trying to?
Most definitely

Feel free to suggest any improvement over the patch.

**Comment by janbender** [comment]
Thanks for the patch. I will take a closer look at it after the Siggraph deadline.

**Comment by louen** [comment]
Thanks for having a look & good luck for SIGGRAPH :)
