### ISSUE TITLE
does the self collision feature cover in this repostory?

### ISSUE THREAD

**Issue by zeagle01** [InteractiveComputerGraphics/PositionBasedDynamics#50]
Dear authors:
I had gone through the readme, and I got the impression that the repostory is mainly about combine pbd and sdf, and I knew sdf can't handle self collision,so I assum that this repostory doesn't support self collision featured cloth simulation. Am I right? Please let me know, thank you!

**Comment by janbender** [comment]
The repository is mainly about PBD and currently we use SDFs for the rigid body collision detection. I see no reason why we shouldn't be able to handle self-collisions using SDFs. However, using SDF in combination with deformable solids is not straight-forward and currently not implemented and for cloth simulations SDFs cannot be used since cloth models do not have a volume. Probably we will integrate a typical triangle mesh collision detection in future to handle cloth models.

**Comment by zeagle01** [comment]
thank you for your reply!
but I'm a little confused.
Giving cloth do not have a volume,how should we be able to applied SDF to handle self-collision

**Comment by janbender** [comment]
We won't use SDFs for cloth but for volumetric deformable solids which can also have self-collisions.
