### ISSUE TITLE
Licensing and patents

### ISSUE THREAD

**Issue by korzen** [InteractiveComputerGraphics/PositionBasedDynamics#58]
Hello,

I assume if the PBD library is using MIT license I am allowed to use it in my commercial software?

I just wanted to make sure that the use of included algorithms for softbodies, elastic rods and so on (basically the things from references section in this Git repo) is also not restricted in any way (i.e. patented). Is it? For instance, I heard somewhere that PBD itself is patented by Matthias Mueller (currently at NVidia.)

Thanks for clarification

Best regards

**Comment by janbender** [comment]
> I assume if the PBD library is using MIT license I am allowed to use it in my commercial software?

Yes. 

> I just wanted to make sure that the use of included algorithms for softbodies, elastic rods and so on (basically the things from references section in this Git repo) is also not restricted in any way (i.e. patented). Is it? For instance, I heard somewhere that PBD itself is patented by Matthias Mueller (currently at NVidia.)

There might be a patent for PBD. I cannot tell you if this is relevant since the PBD method is a classical Lagrange multiplier method which is a well-known approach from classical mechanics. It is even easy to prove that PBD is equivalent to an impulse-based method which was published before.  Btw. it was Matthias Mueller who first has the idea to implement this open-source PBD library and he helped me with the code. But if you want to be sure, you should speak with someone who knows more about patents.

**Comment by korzen** [comment]
Thank you Jan, 

so the published solutions and algorithms from you and your research group (from the references) are not patented or restricted in any way and its OK to use them also commercially?

Best regards

**Comment by janbender** [comment]
We didn't patent any of the methods published by our group. However, I cannot give you any guarantee for the other methods.

**Comment by korzen** [comment]
Thank you
